# Generated by Django 5.2 on 2025-04-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gul', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default=1, verbose_name='Delivery Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=1, max_length=20, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
