services:
  - type: web
    name: gulqand-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py makemigrations
      python manage.py migrate
      echo "from django.contrib.auth import get_user_model; \
            User = get_user_model(); \
            User.objects.filter(username='admin').exists() or \
            User.objects.create_superuser('admin', 'admin@example.com', 'adminpass')" \
            | python manage.py shell
    startCommand: gunicorn gulqand.wsgi:application
